package com.example.myapplication.labs.ghost.emergence

import com.example.myapplication.data.BehaviorEvent
import com.example.myapplication.ui.model.StudentUiItem
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import io.mockk.every
import io.mockk.mockk
import androidx.compose.runtime.mutableStateOf

class GhostEmergenceEngineTest {

    private val engine = GhostEmergenceEngine()

    @Test
    fun `test initial grid is empty`() {
        val grid = engine.getGrid()
        assertEquals(100, grid.size)
        grid.forEach { assertEquals(0f, it) }
    }

    @Test
    fun `test positive impulse increases vitality`() {
        val student = mockk<StudentUiItem>()
        every { student.id } returns 1
        every { student.xPosition.value } returns 2000f
        every { student.yPosition.value } returns 2000f

        val event = BehaviorEvent(studentId = 1, type = "Positive Participation", timestamp = System.currentTimeMillis())

        val grid = engine.update(listOf(student), listOf(event))

        val idx = 5 * 10 + 5
        assertTrue("Vitality at (5,5) should be positive", grid[idx] > 0)
    }

    @Test
    fun `test negative impulse decreases vitality`() {
        val student = mockk<StudentUiItem>()
        every { student.id } returns 1
        every { student.xPosition.value } returns 2000f
        every { student.yPosition.value } returns 2000f

        val event = BehaviorEvent(studentId = 1, type = "Negative Outburst", timestamp = System.currentTimeMillis())

        val grid = engine.update(listOf(student), listOf(event))

        val idx = 5 * 10 + 5
        assertTrue("Vitality at (5,5) should be negative", grid[idx] < 0)
    }

    @Test
    fun `test diffusion spreads vitality to neighbors`() {
        val student = mockk<StudentUiItem>()
        every { student.id } returns 1
        every { student.xPosition.value } returns 2000f
        every { student.yPosition.value } returns 2000f

        val event = BehaviorEvent(studentId = 1, type = "Positive", timestamp = System.currentTimeMillis())

        // Iteration 1: Impulse at (5, 5)
        engine.update(listOf(student), listOf(event))

        // Iteration 2: Diffusion should spread to (5, 6)
        val grid = engine.update(listOf(student), emptyList())

        val neighborIdx = 6 * 10 + 5
        assertTrue("Vitality should diffuse to neighbor", grid[neighborIdx] > 0)
    }

    @Test
    fun `test analyzeEmergence calculates correct metrics`() {
        val grid = FloatArray(100)
        grid[10] = 0.5f  // Positive cluster
        grid[20] = 0.8f  // Positive cluster
        grid[30] = -0.3f // Negative void
        grid[40] = 0.05f // Neutral

        val analysis = engine.analyzeEmergence(grid)

        assertEquals(2, analysis.posCount)
        assertEquals(1, analysis.negCount)
        assertEquals(0.8f, analysis.peakVitality, 0.001f)
        assertEquals(-0.3f, analysis.voidVitality, 0.001f)
        assertEquals("Growth Dominant", analysis.status)
    }

    @Test
    fun `test analyzeEmergence detects decay warning`() {
        val grid = FloatArray(100)
        grid[10] = -0.5f
        grid[20] = -0.8f
        grid[30] = 0.15f

        val analysis = engine.analyzeEmergence(grid)

        assertEquals(1, analysis.posCount)
        assertEquals(2, analysis.negCount)
        assertEquals("Decay Warning", analysis.status)
    }

    @Test
    fun `test generateEmergenceReport output format`() {
        val analysis = GhostEmergenceEngine.EmergenceAnalysis(
            posCount = 5,
            negCount = 2,
            peakVitality = 0.85f,
            voidVitality = -0.42f,
            status = "Growth Dominant"
        )

        val report = engine.generateEmergenceReport(analysis)

        assertTrue(report.contains("# Ghost Emergence Analysis Report"))
        assertTrue(report.contains("Emergent Clusters (Positive): 5"))
        assertTrue(report.contains("Emergent Voids (Negative): 2"))
        assertTrue(report.contains("Peak Vitality: 0.85"))
        assertTrue(report.contains("Maximum Entropy/Void: -0.42"))
        assertTrue(report.contains("Status: Growth Dominant"))
        assertTrue(report.contains("*Generated by Ghost Emergence Engine v1.0 (Experimental)*"))
    }
}
