package com.example.myapplication.labs.ghost.architect

import android.content.Intent
import android.graphics.RuntimeShader
import android.os.Build
import androidx.compose.animation.core.*
import androidx.compose.foundation.Canvas
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.ShaderBrush
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

/**
 * GhostArchitectDialog: A strategic interface for classroom layout optimization reports.
 *
 * Displays the Markdown-formatted "Strategic Layout Report" generated by the [GhostArchitectEngine]
 * within a glassmorphic, AGSL-backed dialog.
 */
@Composable
fun GhostArchitectDialog(
    report: String,
    onDismiss: () -> Unit
) {
    val context = LocalContext.current

    AlertDialog(
        onDismissRequest = onDismiss,
        title = {
            Text(
                text = "GHOST ARCHITECT: STRATEGIC REPORT",
                style = MaterialTheme.typography.titleLarge.copy(
                    color = Color.Cyan,
                    fontWeight = FontWeight.Bold,
                    letterSpacing = 1.2.sp
                )
            )
        },
        text = {
            Column(
                modifier = Modifier
                    .fillMaxWidth()
                    .heightIn(max = 400.dp)
                    .verticalScroll(rememberScrollState()),
                horizontalAlignment = Alignment.CenterHorizontally
            ) {
                // Blueprint Shader Background Box
                Box(
                    modifier = Modifier
                        .fillMaxWidth()
                        .height(120.dp)
                        .padding(vertical = 8.dp)
                ) {
                    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
                        val infiniteTransition = rememberInfiniteTransition(label = "blueprint_pulse")
                        val time by infiniteTransition.animateFloat(
                            initialValue = 0f,
                            targetValue = 6.28f,
                            animationSpec = infiniteRepeatable(
                                animation = tween(4000, easing = LinearEasing),
                                repeatMode = RepeatMode.Restart
                            ),
                            label = "time"
                        )

                        val shader = remember { RuntimeShader(GhostArchitectShader.BLUEPRINT_SHADER) }
                        val brush = remember(shader) { ShaderBrush(shader) }

                        Canvas(modifier = Modifier.fillMaxSize()) {
                            shader.setFloatUniform("uResolution", size.width, size.height)
                            shader.setFloatUniform("uTime", time)
                            shader.setFloatUniform("uAlpha", 1.0f)
                            drawRect(brush = brush)
                        }
                    } else {
                        Surface(
                            modifier = Modifier.fillMaxSize(),
                            color = Color.DarkGray.copy(alpha = 0.3f),
                            shape = MaterialTheme.shapes.medium
                        ) {
                            Box(contentAlignment = Alignment.Center) {
                                Text("Strategic Visualizer (API 33+)", color = Color.Gray)
                            }
                        }
                    }
                }

                // Report Content
                Surface(
                    color = Color.Black.copy(alpha = 0.3f),
                    shape = MaterialTheme.shapes.small,
                    modifier = Modifier.fillMaxWidth().padding(top = 8.dp)
                ) {
                    Text(
                        text = report,
                        style = MaterialTheme.typography.bodySmall.copy(
                            fontFamily = FontFamily.Monospace,
                            lineHeight = 16.sp,
                            color = Color.LightGray
                        ),
                        modifier = Modifier.padding(12.dp)
                    )
                }
            }
        },
        confirmButton = {
            TextButton(
                onClick = {
                    val intent = Intent(Intent.ACTION_SEND).apply {
                        type = "text/plain"
                        putExtra(Intent.EXTRA_SUBJECT, "Ghost Architect: Strategic Report")
                        putExtra(Intent.EXTRA_TEXT, report)
                    }
                    context.startActivity(Intent.createChooser(intent, "Share Strategic Report"))
                }
            ) {
                Text("EXPORT REPORT", color = Color.Cyan)
            }
        },
        dismissButton = {
            TextButton(onClick = onDismiss) {
                Text("CLOSE")
            }
        },
        containerColor = Color(0xFF001212),
        textContentColor = Color.LightGray
    )
}
