package com.example.myapplication.data.importer

import kotlinx.serialization.Serializable

/**
 * Classroom: Data model for the root "Classroom" object in legacy Python exports.
 *
 * This structure reflects the schema of the JSON files generated by the Python desktop
 * application. It is used by the [JsonImporter] for legacy fragmented data ingestion.
 *
 * @property students A map of student IDs (UUID strings) to [Student] data.
 * @property furniture A map of furniture IDs to [Furniture] data.
 * @property behavior_log A list of behavior log entries.
 * @property homework_log A list of homework log entries.
 * @property settings Application-level settings from the desktop app.
 * @property last_excel_export_path Path to the last generated Excel report on the desktop.
 * @property _per_student_last_cleared Timestamps of when each student's logs were last cleared.
 * @property undo_stack Historical command actions for undoing.
 * @property redo_stack Historical command actions for redoing.
 * @property guides A map of alignment guides on the seating chart.
 * @property next_guide_id_num The sequence number for the next guide ID.
 */
@Serializable
data class Classroom(
    val students: Map<String, Student>,
    val furniture: Map<String, Furniture>,
    val behavior_log: List<BehaviorLogEntry>,
    val homework_log: List<HomeworkLogEntry>,
    val settings: Settings,
    val last_excel_export_path: String?,
    val _per_student_last_cleared: Map<String, String>,
    val undo_stack: List<Map<String, @Serializable(with = AnySerializer::class) Any>>,
    val redo_stack: List<Map<String, @Serializable(with = AnySerializer::class) Any>>,
    val guides: Map<String, Guide>,
    val next_guide_id_num: Int
)

/**
 * Student: Legacy data model representing a student in Python-style JSON.
 *
 * This structure corresponds to the student data exported from the Python desktop application.
 *
 * @property firstName Legal first name.
 * @property lastName Legal last name.
 * @property nickname Optional familiar name.
 * @property fullName Pre-concatenated full name.
 * @property gender Student gender ("Boy" or "Girl").
 * @property x Horizontal coordinate in the 2000x1500 logical space.
 * @property y Vertical coordinate in the 2000x1500 logical space.
 * @property id String-based UUID.
 * @property width Icon width in logical pixels.
 * @property height Icon height in logical pixels.
 * @property originalNextIdNumAfterAdd Internal sequence tracking from the Python app.
 * @property groupId The string ID of the group this student belongs to.
 * @property styleOverrides Individual visual customizations.
 */
@Serializable
data class Student(
    @kotlinx.serialization.SerialName("first_name") val firstName: String,
    @kotlinx.serialization.SerialName("last_name") val lastName: String,
    val nickname: String,
    @kotlinx.serialization.SerialName("full_name") val fullName: String,
    val gender: String,
    val x: Double,
    val y: Double,
    val id: String,
    val width: Double,
    val height: Double,
    @kotlinx.serialization.SerialName("original_next_id_num_after_add") val originalNextIdNumAfterAdd: Int,
    @kotlinx.serialization.SerialName("group_id") val groupId: String?,
    @kotlinx.serialization.SerialName("style_overrides") val styleOverrides: StyleOverrides
)

/**
 * StyleOverrides: Visual customization options for a student icon in legacy exports.
 */
@Serializable
data class StyleOverrides(
    val fill_color: String?,
    val outline_color: String?,
    val font_family: String?,
    val font_size: Int?,
    val font_color: String?,
    val width: Double?,
    val height: Double?
)

/**
 * Furniture: Legacy data model for classroom furniture objects.
 */
@Serializable
data class Furniture(
    val name: String,
    val type: String,
    val x: Double,
    val y: Double,
    val id: String,
    val width: Double,
    val height: Double,
    val fill_color: String,
    val outline_color: String,
    val original_next_id_num_after_add: Int
)

/**
 * BehaviorLogEntry: Legacy data model for a behavior incident log.
 */
@Serializable
data class BehaviorLogEntry(
    val timestamp: String,
    val student_id: String,
    val student_first_name: String,
    val student_last_name: String,
    val behavior: String,
    val comment: String,
    val type: String,
    val day: String
)

/**
 * HomeworkLogEntry: Legacy data model for a homework completion log.
 */
@Serializable
data class HomeworkLogEntry(
    val timestamp: String,
    val student_id: String,
    val student_first_name: String,
    val student_last_name: String,
    val behavior: String,
    val homework_type: String,
    val homework_status: String,
    val comment: String,
    val type: String,
    val day: String,
    val marks_data: Map<String, Double>?,
    val num_items: Int?
)

/**
 * Settings: Desktop application settings in legacy exports.
 */
@Serializable
data class Settings(
    val encrypt_data_files: Boolean,
    val app_password_hash: String?
)

/**
 * Guide: Legacy data model for seating chart alignment guides.
 */
@Serializable
data class Guide(
    val id: String,
    val type: String,
    val world_coord: Double
)
