package com.example.myapplication.data.importer

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * PythonClassroomData: A specialized DTO for legacy fragmented data ingestion.
 *
 * This structure is used exclusively by [JsonImporter] to ingest data from older
 * or individual JSON exports generated by the Python desktop application. It mirrors
 * the [ClassroomDataDto] but provides the specific structural mappings required
 * for non-unified ingestion flows.
 */
@Serializable
data class PythonClassroomData(
    val students: Map<String, PythonStudent>,
    val furniture: Map<String, PythonFurniture>,
    @SerialName("behavior_log")
    val behaviorLog: List<PythonBehaviorLog>,
    @SerialName("homework_log")
    val homeworkLog: List<PythonHomeworkLog>
)

/**
 * PythonStudent: Legacy student representation for fragmented ingestion.
 *
 * Used when importing students from a standalone `students.json` or as part
 * of a [PythonClassroomData] collection.
 *
 * ### Key Difference:
 * Unlike [StudentDto], this structure expects a non-nullable [nickname] and [groupId],
 * reflecting the strict schema requirements of early Python desktop versions.
 */
@Serializable
data class PythonStudent(
    @SerialName("first_name")
    val firstName: String,
    @SerialName("last_name")
    val lastName: String,
    val nickname: String,
    val gender: String,
    val x: Double,
    val y: Double,
    @SerialName("style_overrides")
    val styleOverrides: PythonStyleOverrides,
    @SerialName("group_id")
    val groupId: String
)

@Serializable
data class PythonStyleOverrides(
    val width: Double? = null,
    val height: Double? = null,
    @SerialName("fill_color")
    val fillColor: String? = null,
    @SerialName("outline_color")
    val outlineColor: String? = null,
    @SerialName("text_color")
    val textColor: String? = null
)

@Serializable
data class PythonFurniture(
    val name: String,
    val type: String,
    val x: Double,
    val y: Double,
    val width: Double,
    val height: Double,
    @SerialName("fill_color")
    val fillColor: String,
    @SerialName("outline_color")
    val outlineColor: String
)

/**
 * PythonBehaviorLog: Specialized DTO for historical behavior incident ingestion.
 *
 * Maps directly to the `behavior_log` entries in Python desktop exports. These
 * are processed by [JsonImporter] to populate Android's [com.example.myapplication.data.BehaviorEvent] table.
 */
@Serializable
data class PythonBehaviorLog(
    @SerialName("student_id")
    val studentId: String,
    val timestamp: String,
    val behavior: String,
    val comment: String
)

/**
 * PythonHomeworkLog: Specialized DTO for historical homework record ingestion.
 *
 * Facilitates the migration of complex homework statuses and optional `homework_details`
 * maps from the desktop environment to Android's [com.example.myapplication.data.HomeworkLog].
 */
@Serializable
data class PythonHomeworkLog(
    @SerialName("student_id")
    val studentId: String,
    val timestamp: String,
    @SerialName("homework_type")
    val homeworkType: String,
    val behavior: String,
    val comment: String,
    @SerialName("homework_details")
    val homeworkDetails: Map<String, String>? = null
)

@Serializable
data class PythonStudentGroup(
    val name: String,
    val color: String
)

@Serializable
data class PythonCustomBehavior(
    val name: String
)

@Serializable
data class PythonCustomHomeworkStatus(
    val name: String
)

@Serializable
data class PythonCustomHomeworkType(
    val name: String
)

@Serializable
data class PythonHomeworkTemplate(
    val name: String,
    val steps: List<PythonHomeworkMarkStep>
)

@Serializable
data class PythonHomeworkMarkStep(
    val label: String,
    val type: String,
    @SerialName("max_value")
    val maxValue: Int = 1
)
