package com.example.myapplication.data

import androidx.room.Entity
import androidx.room.PrimaryKey
import kotlinx.serialization.Serializable

/**
 * Represents a scheduled reminder for a teacher.
 * Reminders are stored in the local Room database and scheduled via [android.app.AlarmManager].
 *
 * @property id Unique identifier for the reminder, auto-generated by the database.
 * @property title The brief title of the reminder (e.g., "Prep Quiz").
 * @property description Detailed text for the reminder notification.
 * @property timestamp The exact time (in epoch milliseconds) when the reminder should trigger.
 */
@Serializable
@Entity(tableName = "reminders")
data class Reminder(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val title: String,
    val description: String,
    val timestamp: Long
)