import math
import random

def analyze_ghost_ray_intersection(ray_source, ray_target, students, hit_radius=60.0):
    """
    Simulates the Ghost Ray spatial intersection logic for offline analysis.

    This function maintains logic parity with GhostRayEngine.kt. It calculates
    which student nodes are intersected by the ray cast from a device in 3D space,
    projected onto the 2D classroom map.

    Args:
        ray_source (tuple): (x, y) source of the ray (device position).
        ray_target (tuple): (x, y) current target point of the ray.
        students (list): List of student dictionaries with 'id', 'x', and 'y'.
        hit_radius (float): Intersection threshold in logical units.

    Returns:
        int: The ID of the intersected student, or None if no intersection found.
    """
    intersected_id = None
    min_dist = float('inf')

    for student in students:
        sid = student.get('id')
        sx = student.get('x', 0)
        sy = student.get('y', 0)

        # Calculate Euclidean distance between ray target and student node
        dx = sx - ray_target[0]
        dy = sy - ray_target[1]
        dist = math.sqrt(dx * dx + dy * dy)

        if dist < hit_radius:
            if dist < min_dist:
                min_dist = dist
                intersected_id = sid

    return intersected_id

def generate_ray_report(intersected_id, student_name, timestamp=None):
    """
    Generates a futuristic Markdown report for a Ghost Ray intersection event.
    """
    if timestamp is None:
        import datetime
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    report = []
    report.append("# 👻 GHOST RAY: NEURAL TARGETING LOG")
    report.append(f"**Target Locked:** {student_name if student_name else 'NONE'}")
    report.append(f"**Intersection ID:** {intersected_id if intersected_id else 'VOID'}")
    report.append(f"**Timestamp:** {timestamp}")
    report.append("\n---")

    if intersected_id:
        report.append("\n## [SPATIAL TELEMETRY]")
        report.append("- Intersection State: CRITICAL")
        report.append("- Neural Alignment: FOCUSING")
        report.append("- Data Stream: ACTIVE")
    else:
        report.append("\n## [SCANNING STATUS]")
        report.append("- State: SEARCHING")
        report.append("- Field Density: NOMINAL")

    report.append("\n---\n*Generated by Ghost Ray Spatial Bridge v1.0 (PoC 2027)*")
    return "\n".join(report)

if __name__ == "__main__":
    # Mock classroom data
    mock_students = [
        {"id": 1, "name": "Alice", "x": 400, "y": 400},
        {"id": 2, "name": "Bob", "x": 1200, "y": 400},
        {"id": 3, "name": "Charlie", "x": 800, "y": 1200}
    ]

    # Mock ray state (pointing at Alice)
    mock_target = (410, 395)

    intersected_id = analyze_ghost_ray_intersection((600, 2000), mock_target, mock_students)
    student_name = next((s['name'] for s in mock_students if s['id'] == intersected_id), None)

    print(generate_ray_report(intersected_id, student_name))
