import json
import math
from datetime import datetime

"""
Ghost Architect Analysis Bridge v1.0
------------------------------------
This script mirrors the logical heuristics of the GhostArchitectEngine
to calculate 'Layout Synergy' and 'Strategic Alignment' scores for a classroom.
"""

class GhostArchitect:
    def __init__(self, students, edges, behavior_logs):
        self.students = {s['id']: s for s in students}
        self.edges = edges
        self.behavior_logs = behavior_logs

    def calculate_synergy(self, goal):
        """
        Calculates a global synergy score (0.0 to 1.0) based on how well
        the current layout matches a pedagogical goal.
        """
        score = 0.0
        n_students = len(self.students)
        if n_students == 0: return 0.0

        if goal == "COLLABORATION":
            # High synergy if collaborators are close (< 300 units)
            collab_edges = [e for e in self.edges if e['type'] == "COLLABORATION"]
            if not collab_edges: return 1.0

            total_dist = 0
            for edge in collab_edges:
                s1 = self.students.get(edge['fromId'])
                s2 = self.students.get(edge['toId'])
                if s1 and s2:
                    dx = s1['xPosition'] - s2['xPosition']
                    dy = s1['yPosition'] - s2['yPosition']
                    dist = math.sqrt(dx**2 + dy**2)
                    total_dist += min(dist, 1000)

            avg_dist = total_dist / len(collab_edges)
            score = 1.0 - (avg_dist / 1000.0)

        elif goal == "FOCUS":
            # High synergy if friction points are far (> 800 units)
            friction_edges = [e for e in self.edges if e['type'] == "FRICTION"]
            if not friction_edges: return 1.0

            total_dist = 0
            for edge in friction_edges:
                s1 = self.students.get(edge['fromId'])
                s2 = self.students.get(edge['toId'])
                if s1 and s2:
                    dx = s1['xPosition'] - s2['xPosition']
                    dy = s1['yPosition'] - s2['yPosition']
                    dist = math.sqrt(dx**2 + dy**2)
                    total_dist += min(dist, 1500)

            avg_dist = total_dist / len(friction_edges)
            score = (avg_dist / 1500.0)

        return round(score, 4)

    def generate_report(self):
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        collab_score = self.calculate_synergy("COLLABORATION")
        focus_score = self.calculate_synergy("FOCUS")

        report = f"""
# 🏗️ GHOST ARCHITECT: STRATEGIC LAYOUT REPORT
**Generated:** {timestamp}
**Classroom Sample:** {len(self.students)} students

## 🛰️ Neural Alignment Metrics
- **Collaboration Synergy:** {collab_score * 100}%
- **Focus Reliability:** {focus_score * 100}%

---
*Generated by Ghost Architect Python Bridge v1.0 (Experimental)*
"""
        return report

def main():
    # Mock data for parity testing
    students = [
        {"id": 1, "firstName": "Alice", "xPosition": 500, "yPosition": 500},
        {"id": 2, "firstName": "Bob", "xPosition": 600, "yPosition": 550},
        {"id": 3, "firstName": "Charlie", "xPosition": 2000, "yPosition": 2000}
    ]
    edges = [
        {"fromId": 1, "toId": 2, "type": "COLLABORATION"},
        {"fromId": 1, "toId": 3, "type": "FRICTION"}
    ]

    architect = GhostArchitect(students, edges, [])
    print(architect.generate_report())

if __name__ == "__main__":
    main()
