import json
import math
import sys
from datetime import datetime

def analyze_vortices(classroom_data):
    """
    Analyzes student data to identify rotational social momentum clusters (Vortices).

    This script implements a "Social Whirlpool" model where clusters of students
    with high activity create localized social vortices with angular momentum.

    Args:
        classroom_data (dict): The classroom data including student positions and behavior logs.

    Returns:
        str: A Markdown-formatted report of the detected classroom vortices.
    """
    students = classroom_data.get('students', [])
    logs = classroom_data.get('behavior_events', [])

    # Analysis Window: 10 minutes (matches Kotlin engine)
    current_time_ms = int(datetime.now().timestamp() * 1000)
    window_ms = 600000

    # FIX FOR DEMO: Use a very large window or force timestamps to be recent
    recent_logs = [l for l in logs if current_time_ms - l.get('timestamp', 0) < window_ms]

    # If we are in demo mode and no recent logs, just use all logs for simulation
    if not recent_logs and not classroom_data.get('real_data', False):
        recent_logs = logs

    # Calculate student "Energy"
    student_energy = {}
    for s in students:
        sid = s['id']
        s_logs = [l for l in recent_logs if l.get('studentId') == sid]

        pos_count = len([l for l in s_logs if "Negative" not in l.get('type', "")])
        neg_count = len([l for l in s_logs if "Negative" in l.get('type', "")])

        polarity = -1.0 if neg_count > pos_count else 1.0
        intensity = min(len(s_logs) / 5.0, 1.0)

        student_energy[sid] = {'intensity': intensity, 'polarity': polarity}

    vortices = []
    cluster_threshold = 800.0

    for s1 in students:
        energy = student_energy.get(s1['id'], {}).get('intensity', 0)
        if energy > 0.4:
            # Check if near existing
            is_near = False
            for v in vortices:
                dist = math.sqrt((v['x'] - s1['x_position'])**2 + (v['y'] - s1['y_position'])**2)
                if dist < cluster_threshold:
                    is_near = True
                    break

            if not is_near:
                neighbors = []
                for s2 in students:
                    if s1['id'] == s2['id']: continue
                    dist = math.sqrt((s1['x_position'] - s2['x_position'])**2 + (s1['y_position'] - s2['y_position'])**2)
                    if dist < cluster_threshold:
                        neighbors.append(s2)

                if neighbors:
                    neighbor_energy = sum([student_energy.get(n['id'], {}).get('intensity', 0) for n in neighbors])
                    neighbor_polarity = sum([student_energy.get(n['id'], {}).get('polarity', 1.0) for n in neighbors])

                    avg_energy = (energy + neighbor_energy) / (len(neighbors) + 1)
                    avg_polarity = (student_energy[s1['id']]['polarity'] + neighbor_polarity) / (len(neighbors) + 1)

                    vortices.append({
                        'x': s1['x_position'],
                        'y': s1['y_position'],
                        'momentum': min(max(avg_energy, 0.1), 1.0),
                        'polarity': 1.0 if avg_polarity >= 0 else -1.0,
                        'student_name': s1.get('full_name', f"Student {s1['id']}")
                    })

    vortices.sort(key=lambda x: x['momentum'], reverse=True)

    report = f"""
# 🌀 GHOST VORTEX: ROTATIONAL SOCIAL ANALYSIS
**Classroom Momentum Index:** {sum([v['momentum'] for v in vortices]) / len(students) if students else 0:.2f}
**Detected Vortices:** {len(vortices)}
**Timestamp:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

---

## 🌪️ Behavioral Cyclones
Localized spirals of social energy detected in the classroom grid.

| Center Node | Angular Momentum | Social Polarity | Status |
| :--- | :--- | :--- | :--- |
"""
    for v in vortices:
        polarity_str = "POSITIVE (SYNERGY)" if v['polarity'] > 0 else "NEGATIVE (DISTRACTION)"
        status = "HIGH ENERGY" if v['momentum'] > 0.7 else "STABLE ROTATION"
        report += f"| {v['student_name']} | {v['momentum']:.2f} | {polarity_str} | {status} |\n"

    if not vortices:
        report += "| N/A | 0.00 | NEUTRAL | FLAT |\n"

    report += "\n---\n*Generated by Ghost Vortex Analysis Bridge v1.0 (Experimental)*"
    return report

if __name__ == "__main__":
    if len(sys.argv) > 1:
        try:
            with open(sys.argv[1], 'r') as f:
                data = json.load(f)
                data['real_data'] = True
                print(analyze_vortices(data))
        except Exception as e:
            print(f"❌ Error during analysis: {e}")
    else:
        demo_data = {
            'students': [
                {'id': 1, 'x_position': 100, 'y_position': 100, 'full_name': 'Alpha'},
                {'id': 2, 'x_position': 150, 'y_position': 150, 'full_name': 'Bravo'},
                {'id': 3, 'x_position': 200, 'y_position': 200, 'full_name': 'Charlie'}
            ],
            'behavior_events': [
                {'studentId': 1, 'timestamp': int(datetime.now().timestamp() * 1000) - 1000, 'type': 'Participating'},
                {'studentId': 2, 'timestamp': int(datetime.now().timestamp() * 1000) - 1000, 'type': 'Participating'},
                {'studentId': 3, 'timestamp': int(datetime.now().timestamp() * 1000) - 1000, 'type': 'Participating'},
                {'studentId': 1, 'timestamp': int(datetime.now().timestamp() * 1000) - 1000, 'type': 'Participating'},
                {'studentId': 2, 'timestamp': int(datetime.now().timestamp() * 1000) - 1000, 'type': 'Participating'},
                {'studentId': 3, 'timestamp': int(datetime.now().timestamp() * 1000) - 1000, 'type': 'Participating'},
                {'studentId': 1, 'timestamp': int(datetime.now().timestamp() * 1000) - 1000, 'type': 'Participating'},
                {'studentId': 2, 'timestamp': int(datetime.now().timestamp() * 1000) - 1000, 'type': 'Participating'},
                {'studentId': 3, 'timestamp': int(datetime.now().timestamp() * 1000) - 1000, 'type': 'Participating'}
            ]
        }
        print("🌀 Running in DEMO mode with synthetic social spirals...")
        print(analyze_vortices(demo_data))
