import json
import math
import sys

def analyze_vectors(classroom_data):
    """
    Analyzes student data to calculate social gravity vectors and classroom cohesion.

    This script implements a "Social Gravity" model where students exert forces on
    one another based on their proximity and behavioral history (collaboration
    vs friction). It calculates a net force vector for each student, indicating
    their current "Social Momentum."

    Args:
        classroom_data (dict): The classroom data including student positions.

    Returns:
        str: A Markdown-formatted report of the classroom's social cohesion metrics.
    """
    students = classroom_data.get('students', [])

    def calculate_distance(s1, s2):
        return math.sqrt((s1.get('x_position', 0) - s2.get('x_position', 0))**2 +
                         (s1.get('y_position', 0) - s2.get('y_position', 0))**2)

    student_vectors = {}
    for s in students:
        student_vectors[s['id']] = {'dx': 0, 'dy': 0, 'name': s.get('full_name', f"Student {s['id']}")}

    # Simulate Social Force Summation
    for i, s1 in enumerate(students):
        for j, s2 in enumerate(students):
            if i < j:
                dist = calculate_distance(s1, s2)
                # Proximity-based force threshold
                if dist < 800:
                    # Mock relationship determination (mirrors GhostLatticeEngine logic)
                    # In a production bridge, this would use actual behavioral log correlation.
                    rel_seed = (s1['id'] * s2['id'] + 42) % 100
                    strength = (1.0 - (dist / 1200.0))

                    force = 0
                    if rel_seed > 70:    # Collaboration (Attraction)
                        force = strength * 60
                    elif rel_seed < 15:  # Friction (Repulsion)
                        force = -strength * 100
                    else:                # Neutral (Mild Attraction)
                        force = strength * 15

                    dx = s2.get('x_position', 0) - s1.get('x_position', 0)
                    dy = s2.get('y_position', 0) - s1.get('y_position', 0)
                    dist = max(dist, 1.0)

                    dir_x = dx / dist
                    dir_y = dy / dist

                    student_vectors[s1['id']]['dx'] += dir_x * force
                    student_vectors[s1['id']]['dy'] += dir_y * force
                    student_vectors[s2['id']]['dx'] -= dir_x * force
                    student_vectors[s2['id']]['dy'] -= dir_y * force

    # Compile results and metrics
    cohesion_scores = []
    results = []
    for sid, data in student_vectors.items():
        mag = math.sqrt(data['dx']**2 + data['dy']**2)
        cohesion_scores.append(mag)

        status = "NOMINAL"
        if mag > 85: status = "HIGH TURBULENCE"
        elif mag < 5: status = "ISOLATED"
        elif mag > 40: status = "ACTIVE SYNERGY"

        results.append({
            'name': data['name'],
            'magnitude': mag,
            'status': status
        })

    avg_cohesion = sum(cohesion_scores) / len(cohesion_scores) if cohesion_scores else 0

    report = f"""
# 👻 GHOST VECTOR: SOCIAL COHESION ANALYSIS
**Classroom Cohesion Index:** {avg_cohesion:.2f}
**Global Status:** {'STABLE' if avg_cohesion < 50 else 'DYNAMIC'}
**Timestamp:** {classroom_data.get('timestamp', 'N/A')}

---

## 🛰️ Neural Trajectory & Turbulence
Each student's 'Net Force' represents their current social momentum within the classroom grid.

| Student | Net Force (mG) | Social Status |
| :--- | :--- | :--- |
"""
    for r in sorted(results, key=lambda x: x['magnitude'], reverse=True):
        report += f"| {r['name']} | {r['magnitude']:.2f} | {r['status']} |\n"

    report += "\n---\n*Generated by Ghost Vector Analysis Bridge v1.0 (Experimental)*"
    return report

if __name__ == "__main__":
    if len(sys.argv) > 1:
        try:
            with open(sys.argv[1], 'r') as f:
                data = json.load(f)
                print(analyze_vectors(data))
        except Exception as e:
            print(f"❌ Error during analysis: {e}")
    else:
        # Mock demonstration mode
        demo_data = {
            'timestamp': '2027-04-12 10:00:00',
            'students': [
                {'id': 1, 'x_position': 100, 'y_position': 100, 'full_name': 'Alpha'},
                {'id': 2, 'x_position': 180, 'y_position': 120, 'full_name': 'Bravo'},
                {'id': 3, 'x_position': 600, 'y_position': 700, 'full_name': 'Charlie'},
                {'id': 4, 'x_position': 650, 'y_position': 680, 'full_name': 'Delta'}
            ]
        }
        print("🌀 Running in DEMO mode with synthetic student nodes...")
        print(analyze_vectors(demo_data))
