package com.example.myapplication.labs.ghost.pulsar

import com.example.myapplication.data.BehaviorEvent
import com.example.myapplication.ui.model.StudentUiItem
import androidx.compose.runtime.mutableStateOf
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

class GhostPulsarEngineTest {

    @Test
    fun testCalculateHarmonics_NoLogs() {
        val students = listOf(mockStudent(1))
        val currentTime = System.currentTimeMillis()
        val harmonics = GhostPulsarEngine.calculateHarmonics(students, emptyList(), currentTime)

        assertEquals(1, harmonics.size)
        assertEquals(0.1f, harmonics[0].frequency, 0.01f) // Base frequency
        assertEquals(0f, harmonics[0].amplitude, 0.01f)   // Zero amplitude
    }

    @Test
    fun testCalculateHarmonics_WithLogs() {
        val students = listOf(mockStudent(1))
        val currentTime = System.currentTimeMillis()
        val events = listOf(
            BehaviorEvent(id = 1, studentId = 1, type = "Positive", timestamp = currentTime - 1000, comment = null),
            BehaviorEvent(id = 2, studentId = 1, type = "Positive", timestamp = currentTime - 5000, comment = null)
        )

        val harmonics = GhostPulsarEngine.calculateHarmonics(students, events, currentTime)

        assertEquals(1, harmonics.size)
        // 2 logs in 10 mins = 0.2 logs/min. Engine clamps freq to 0.1..10.
        // Wait, 2 logs / 10 mins = 0.2. So freq should be 0.2.
        assertEquals(0.2f, harmonics[0].frequency, 0.01f)
        assertEquals(0.4f, harmonics[0].amplitude, 0.01f) // 2 / 5 = 0.4
    }

    @Test
    fun testDetectBonds() {
        val harmonics = listOf(
            GhostPulsarEngine.HarmonicState(1L, 0f, 1.0f, 0.5f),
            GhostPulsarEngine.HarmonicState(2L, 0f, 1.1f, 0.5f), // Diff 0.1 < 0.2
            GhostPulsarEngine.HarmonicState(3L, 0f, 1.3f, 0.5f)  // Diff 0.2 from H2, 0.3 from H1
        )
        val studentNames = mapOf(1L to "Alice", 2L to "Bob", 3L to "Charlie")

        val bonds = GhostPulsarEngine.detectBonds(harmonics, studentNames)

        // Bond 1: Alice & Bob (diff 0.1)
        // Bond 2: Bob & Charlie (diff 0.2) -> wait, the logic is diff < 0.2f
        // So only Alice & Bob should be detected if diff is exactly 0.2? 1.3 - 1.1 = 0.2.
        // Let's check: diff < 0.2f. So 0.2 is NOT included.

        assertEquals(1, bonds.size)
        assertEquals("Alice", bonds[0].studentAName)
        assertEquals("Bob", bonds[0].studentBName)
        assertEquals(0.9f, bonds[0].sync, 0.01f)
    }

    @Test
    fun testGeneratePulsarReport() {
        val harmonics = listOf(
            GhostPulsarEngine.HarmonicState(1L, 0f, 2.0f, 0.5f),
            GhostPulsarEngine.HarmonicState(2L, 0f, 1.0f, 0.3f)
        )
        val bonds = listOf(
            GhostPulsarEngine.HarmonicBond("Alice", "Bob", 0.95f)
        )
        val studentNames = mapOf(1L to "Alice", 2L to "Bob")

        val report = GhostPulsarEngine.generatePulsarReport(harmonics, bonds, studentNames, 2, 10)

        assertTrue(report.contains("# 👻 GHOST PULSAR: CLASSROOM RHYTHM ANALYSIS"))
        assertTrue(report.contains("Analyzing 2 students and 10 logs..."))
        assertTrue(report.contains("| Alice | 2.00 | 0.50 |")) // Sorted by freq DESC
        assertTrue(report.contains("| Bob | 1.00 | 0.30 |"))
        assertTrue(report.contains("## --- Detected Harmonic Bonds (Synchronized Pairs) ---"))
        assertTrue(report.contains("🔗 Bond: Alice <-> Bob (Sync: 0.95)"))
        assertTrue(report.contains("*Generated by Ghost Pulsar Analysis Bridge"))
    }

    private fun mockStudent(id: Int): StudentUiItem {
        return StudentUiItem(
            id = id,
            fullName = mutableStateOf("Test Student"),
            nickname = mutableStateOf(""),
            initials = mutableStateOf("TS"),
            xPosition = mutableStateOf(100f),
            yPosition = mutableStateOf(100f),
            displayWidth = mutableStateOf(100.dp),
            displayHeight = mutableStateOf(100.dp),
            displayBackgroundColor = mutableStateOf(listOf(Color.White)),
            displayOutlineColor = mutableStateOf(listOf(Color.Black)),
            displayTextColor = mutableStateOf(Color.Black),
            displayOutlineThickness = mutableStateOf(2.dp),
            displayCornerRadius = mutableStateOf(8.dp),
            displayPadding = mutableStateOf(4.dp),
            fontFamily = mutableStateOf("SansSerif"),
            fontSize = mutableStateOf(12),
            fontColor = mutableStateOf(Color.Black),
            recentBehaviorDescription = mutableStateOf(emptyList()),
            recentHomeworkDescription = mutableStateOf(emptyList()),
            recentQuizDescription = mutableStateOf(emptyList()),
            groupColor = mutableStateOf(null),
            groupId = mutableStateOf(null),
            sessionLogText = mutableStateOf(emptyList()),
            temporaryTask = mutableStateOf(null)
        )
    }
}
